require 'txtbook'
require 'rubygems'
require 'rake'

task :default do
  builder = TxtBook::KeynoteBuilder.new(File.expand_path(File.dirname(__FILE__) + "/"))
  builder.unbind
  builder.press
  builder.rebind
end
  
